spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio_final
    username: postgres
    password: Deusfamilia33@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

